language: ruby
rvm:
- 2.1.10
- 2.2.9
- 2.3.6
- 2.4.3
- 2.5.0
script: bundle exec rake
after_success: codeclimate-test-reporter
env:
  global:
    secure: WePtrkj/9oP0jbEFdaOcHm/fee0tzWBA1kTNhrvEiHtgbQWfF4iW4ihov74Up/jCad49furkZ+tuvPfkLdh6Y8t7P7CbaEUe8kOzO5+JCSa2AXq9FzWl7xnxC0/tztjRomHfREpbZBBlacmLvro2JJlIOn+0cAAwoRG+ixSUgtY=
